
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexvion
  namespace: nexvion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexvion
  template:
    metadata:
      labels:
        app: nexvion
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: nexvion
          image: manjulakadari/nexvion:latest
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          volumeMounts:
            - name: nginx-temp
              mountPath: /tmp
      volumes:
        - name: nginx-temp
          emptyDir: {}
