apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexvion
  namespace: nexvion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexvion
  template:
    metadata:
      labels:
        app: nexvion
    spec:
      containers:
        - name: nexvion
          image: manjulakadari/nexvion:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
